### ISSUE TITLE
sendTrx报错

### ISSUE THREAD

**Issue by apayllc** [v03413/php-tron#1]
<br />
<b>Fatal error</b>: Uncaught TypeError: Argument 2 passed to IEXBase\TronAPI\Tron::sendTransaction() must be of the type
float, string given, called in /www/wwwroot/upayouts.pay.vin/vendor/iexbase/tron-api/src/Tron.php on line 826 and
defined in /www/wwwroot/upayouts.pay.vin/vendor/iexbase/tron-api/src/Tron.php:685
Stack trace:
#0 /www/wwwroot/upayouts.pay.vin/vendor/iexbase/tron-api/src/Tron.php(826): IEXBase\TronAPI\Tron-&gt;sendTransaction()
#1 /www/wwwroot/upayouts.pay.vin/Api.php(51): IEXBase\TronAPI\Tron-&gt;sendTrx()
#2 {main}
thrown in <b>/www/wwwroot/upayouts.pay.vin/vendor/iexbase/tron-api/src/Tron.php</b> on line <b>685</b><br />

**Comment by v03413** [comment]
那儿不是写了 `sendTransaction() must be of the type float,`
